### ISSUE TITLE
[TASK] Create pallet-light-proposals

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/pallet-eth2-light-client#24]
### **Goal :** 

The goal of pallet-light-proposals is to verify the block_header and proofs submitted by the relayers and create proposals. The high level flow is :

- Relayer submits the `eth_blockHeader` and merkle proofs to the pallet-light-proposal
- pallet-light-proposals checks its a valid block header by :
	1. Ensure the block_hash generated from the blockHeader is recorded in eth-light-client pallet
	2. Verify the two merkle proofs uploaded : https://github.com/webb-tools/webb-rs/blob/main/bridge-proofs/src/lib.rs
- Make the anchor update proposals and submit to unsigned proposal queue

### Pallet : 

- Extrinsic calls for relayers to submit proposals

```rust

pub struct LightProposalInput<B,P,S> {
  pub block_header : B,
  pub root_merkle_proof : P,
  pub storage_merkle_proof : S
}

#[pallet::call_index(1)]
#[pallet::weight(Weight::from_ref_time(10_000) + T::DbWeight::get().reads_writes(1,1))]
pub fn submit_proposal(origin: OriginFor<T>, proposal : LightProposalInput<>) -> DispatchResultWithPostInfo {
  // generate the block hash
  let block_hash = Self::generate_block_hash(proposal.block_header);

  // validate the block hash against the eth-light-client storage
  ensure!(Self::is_block_hash_valid(block_hash), Error::<T>::InvalidBlock);

 // validate the merkle proofs
 ensure!(Self::validate_merkle_proof(proposal.proof), Error::<T>::InvalidProof);

 // prepare the proposal
Self::prepare_proposal(proposal);
}
```

References : 
https://www.notion.so/hicommonwealth/Proposals-System-v2-311fe027f2e640c4a0170c0281e4a38a

**Comment by drewstone** [comment]
Currently this only supports storage proofs but we can leverage the GGX work to also integrate transaction proofs. Chatting with them might be helpful to see how we can help them.

**Comment by drewstone** [comment]
### Considerations
- We want a verification pallet for verifying tx proofs and storage proofs from any chain w/ supported light client on Tangle
- Built in a way that will in the future be used for TSS as a service
- Modular so that if we want to build `light-proposals` it will consume the verification pallet.

**Comment by drewstone** [comment]
Linking the small example we have for verifying 1 storage key, value.
- https://github.com/webb-tools/protocol-solidity/blob/main/packages/contracts/test/vanchor/vanchor.test.ts#L1285-L1360
- https://github.com/webb-tools/protocol-solidity/blob/main/packages/contracts/test/vanchor/vanchor.test.ts#L1351-L1359

In order to create an AUP, we'll need to likely verify multiple storage proofs
- Storage proof of the latest leaf index
- Storage proof of the latest merkle root
